### ISSUE TITLE
You have violated the JAFFE terms of use

### ISSUE THREAD

**Issue by mmmjjjlll** [hafezgh/JAFFE-Facial-and-Emotion-Recognition#1]
Hello,

I have noticed that you are redistributing the JAFFE images with this repository.
This is a violation of the terms of use.

You must remove all JAFFE images.
If you do not act promptly, I will contact the chair of your university department
to inform them about your violation.

If you act promptly, no further action will be taken.

Michael Lyons
(responsible for JAFFE permissions)

**Comment by hafezgh** [comment]
Hello,

I removed the images. Sorry for the inconvenience.

Regards
Hafez Ghaemi

**Comment by mmmjjjlll** [comment]
Thank you for your prompt action.

Michael Lyons
